### ISSUE TITLE
Noise reducer using notch filter breaks with MNE 0.13

### ISSUE THREAD

**Issue by pravsripad** [jdammers/jumeg#119]
When trying to apply noise reducer to remove notch freq and harmonics,..
```
raw = mne.io.Raw(raw_fname, preload=True)
jumeg.jumeg_noise_reducer.noise_reducer('109925_CAU01A_100715_0842_2_c,rfDC-raw.fif', raw=raw, refnotch=50., verbose=True)
```

Below is the traceback of the error, 
```
psripad@pravmac:~/mne/jumeg_tests $python jumeg_test.py
Opening raw data file /Users/psripad/mne/jumeg_tests/109925_CAU01A_100715_0842_2_c,rfDC-raw.fif...
    Range : 0 ... 165235 =      0.000 ...   162.433 secs
Ready.
Current compensation grade : 0
Reading 0 ... 165235  =      0.000 ...   162.433 secs...
########## Read raw data:
>>> loading raw data took 0.0 ms (0.00 s walltime)
>>> Set time-range to [  0.000,162.433]
>>> Using all refchans.
>>> sigpick: 248 chans, refpick:  23 chans
########## Filter reference channels:
>>> notches at freq 50.0 and harmonics below 250.5
Setting up band-stop filter
Traceback (most recent call last):
  File "jumeg_test.py", line 17, in <module>
    jumeg.jumeg_noise_reducer.noise_reducer('109925_CAU01A_100715_0842_2_c,rfDC-raw.fif', raw=raw, refnotch=50., verbose=True)
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/jumeg/jumeg_noise_reducer.py", line 533, in noise_reducer
    picks=np.array(xrange(nref)), method='iir')
  File "<string>", line 2, in notch_filter
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/utils.py", line 688, in verbose
    return function(*args, **kwargs)
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/io/base.py", line 1181, in notch_filter
    phase=phase, fir_window=fir_window)
  File "<string>", line 2, in notch_filter
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/utils.py", line 688, in verbose
    return function(*args, **kwargs)
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/filter.py", line 1681, in notch_filter
    n_jobs, method, iir_params, copy, phase, fir_window)
  File "<string>", line 2, in filter_data
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/utils.py", line 688, in verbose
    return function(*args, **kwargs)
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/filter.py", line 789, in filter_data
    h_trans_bandwidth, method, iir_params, phase, fir_window)
  File "<string>", line 2, in create_filter
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/utils.py", line 688, in verbose
    return function(*args, **kwargs)
  File "/Users/psripad/miniconda2/lib/python2.7/site-packages/mne/filter.py", line 1052, in create_filter
    raise ValueError('Multiple stop-bands can only be used '
ValueError: Multiple stop-bands can only be used with FIR filtering
```

The problem lies in lines:
```
            if use_refantinotch:
                rawref = raw.copy().drop_channels(droplist)
                freqlast = np.min([5.01 * refnotch, 0.5 * raw.info['sfreq']])
                fltref.notch_filter(np.arange(refnotch, freqlast, refnotch),
                                    picks=np.array(xrange(nref)), method='iir')
                fltref._data = (rawref._data - fltref._data)
```

is it possible to simply use "fir" filter for this case @ebeich ? 

FYI  - @jdammers @fboers

**Comment by pravsripad** [comment]
Pushed a temporary workaround - #121
